# Generated by Django 5.1 on 2024-09-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"], "verbose_name": "Mart Product"},
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="photos/%y/%m/%d"),
        ),
    ]
