# Generated by Django 5.1 on 2024-09-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["price"], "verbose_name": "Mart Product"},
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="photos/%y/%m/%d"),
        ),
    ]
