# Generated by Django 5.1 on 2024-09-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_transaction_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_order_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="products.order"
            ),
        ),
    ]
