# Generated by Django 5.1 on 2024-09-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_order_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
